import { useCallback, useEffect, useState } from 'react';
import { collection, doc, onSnapshot, orderBy, query } from 'firebase/firestore';
import { httpsCallable } from 'firebase/functions';
import { db, ensureAnonymousUser, functions } from './firebase';
import type { MatchEvent, MatchView, PrivateView } from './model';
import { errorMessage } from './model';
import { Lobby } from './components/Lobby';
import { GameBoard } from './components/GameBoard';
import './styles.css';
const storedMatch = () => localStorage.getItem('extreme-hanafuda-match');
export default function App() {
  const [uid, setUid] = useState(''); const [matchId, setMatchId] = useState<string | null>(storedMatch); const [match, setMatch] = useState<MatchView | null>(null); const [privateView, setPrivateView] = useState<PrivateView | null>(null); const [reviewEvents, setReviewEvents] = useState<MatchEvent[]>([]); const [roomCode, setRoomCode] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('匿名認証に接続中…');
  useEffect(() => { ensureAnonymousUser().then((user) => { setUid(user.uid); setMessage(''); }).catch((error) => setMessage(errorMessage(error))); }, []);
  useEffect(() => { if (!uid || !matchId) return; const forgetStaleMatch = () => { setMatch(null); setPrivateView(null); setReviewEvents([]); setMatchId(null); localStorage.removeItem('extreme-hanafuda-match'); setMessage('前回の部屋には参加できません。新しく部屋を作るか、招待コードで参加してください。'); }; const unsubMatch = onSnapshot(doc(db, 'matches', matchId), (snapshot) => { if (snapshot.exists()) setMatch(snapshot.data() as MatchView); else { forgetStaleMatch(); } }, (error) => { if ((error as { code?: string }).code === 'permission-denied') forgetStaleMatch(); else setMessage(errorMessage(error)); }); const unsubPrivate = onSnapshot(doc(db, 'matches', matchId, 'private', uid), (snapshot) => setPrivateView(snapshot.exists() ? snapshot.data() as PrivateView : null), () => setPrivateView(null)); const unsubEvents = onSnapshot(query(collection(db, 'matches', matchId, 'events'), orderBy('createdAt', 'asc')), (snapshot) => setReviewEvents(snapshot.docs.map((event) => ({ id: event.id, ...event.data() }) as MatchEvent)), () => setReviewEvents([])); return () => { unsubMatch(); unsubPrivate(); unsubEvents(); }; }, [matchId, uid]);
  const call = useCallback(async <T,>(name: string, data: unknown): Promise<T> => { setBusy(true); setMessage('処理中…'); try { const result = await httpsCallable(functions, name)(data); setMessage(''); return result.data as T; } catch (error) { setMessage(errorMessage(error)); throw error; } finally { setBusy(false); } }, []);
  const remember = (id: string) => { localStorage.setItem('extreme-hanafuda-match', id); setMatchId(id); };
  const create = async () => { try { remember((await call<{ matchId: string }>('createMatch', {})).matchId); } catch { /* status contains details */ } };
  const join = async () => { try { remember((await call<{ matchId: string }>('joinMatch', { roomCode })).matchId); } catch { /* status contains details */ } };
  const command = async (type: string, payload: unknown) => { if (!matchId || match?.stateVersion === undefined) return; try { await call('submitGameCommand', { matchId, commandId: crypto.randomUUID(), expectedStateVersion: match.stateVersion, type, payload }); } catch { /* listener refreshes stale versions */ } };
  if (!uid || !matchId || !match) return <div className="shell"><header><p className="eyebrow">戦国札合戦</p><h1>エクストリーム<br/>花札</h1><p>ふたりで遊ぶ、一戦決着の花札バトル。</p></header>{message ? <p className="status" role="status">{message}</p> : null}<main className="panel home"><a className="guide-link" href="/how-to-play.html" target="_blank" rel="noreferrer">はじめて遊ぶ人へ：遊び方を読む</a><button className="primary large" type="button" disabled={!uid || busy} onClick={create} data-testid="create-match">部屋を作る</button><div className="divider"><span>または</span></div><label htmlFor="room-code">部屋IDで参加</label><input id="room-code" value={roomCode} maxLength={6} autoComplete="off" onChange={(event) => setRoomCode(event.target.value.toUpperCase().replace(/[^A-Z2-9]/g, ''))} placeholder="ABC234" data-testid="join-code"/><button type="button" disabled={!uid || busy || roomCode.length !== 6} onClick={join} data-testid="join-match">参加する</button></main></div>;
  const leave = () => { localStorage.removeItem('extreme-hanafuda-match'); setMatchId(null); setMatch(null); setPrivateView(null); setReviewEvents([]); };
  return <div className="shell"><header className="compact"><p className="eyebrow">エクストリーム花札</p><h1>{match.status === 'LOBBY' ? '対戦ロビー' : '戦国札合戦'}</h1></header>{message ? <p className="status" role="status">{message}</p> : null}{match.status === 'LOBBY' ? <Lobby match={match} uid={uid} busy={busy} onReady={(ready) => void call('setReady', { matchId, ready }).catch(() => {})} onStart={() => void call('startMatch', { matchId }).catch(() => {})} onLeave={leave}/> : <GameBoard match={match} privateView={privateView} reviewEvents={reviewEvents} uid={uid} busy={busy} onPlay={(cardId) => void command('PLAY_CARD', { cardId })} onMatch={(matchedCardId) => void command('CHOOSE_MATCH', { matchedCardId })} onRematch={() => void call('rematchMatch', { matchId }).catch(() => {})} onForfeit={() => void call('forfeitMatch', { matchId }).catch(() => {})} onTimeout={() => void call('claimTimeout', { matchId }).catch(() => {})}/>}</div>;
}
