import { describe, expect, it } from 'vitest';
import { CARDS, assertInvariants, calculateYaku, forfeitGame, initializeGame, reduceGame, timeoutGame } from '../src/index.js';

describe('game core', () => {
  it('creates a deterministic legal 48-card game', () => { const a = initializeGame(['a', 'b'], 'seed', 123); const b = initializeGame(['a', 'b'], 'seed', 123); expect(a).toEqual(b); expect(CARDS).toHaveLength(48); expect(a.deck).toHaveLength(24); assertInvariants(a); });
  it('rejects a non participant and permits a legal play', () => { const game = initializeGame(['a', 'b'], 'play'); expect(() => reduceGame(game, 'c', { type: 'PLAY_CARD', cardId: game.players[game.activePlayerIndex].hand[0]! })).toThrow(/参加者/); const result = reduceGame(game, game.players[game.activePlayerIndex].uid, { type: 'PLAY_CARD', cardId: game.players[game.activePlayerIndex].hand[0]! }); assertInvariants(result.state); expect(result.events[0]?.type).toBe('PLAY_CARD'); });
  it('scores standard yakus including sake as animal and chaff', () => { const yaku = calculateYaku(['7-1', '10-1', '6-1', '9-1', '8-1', '3-1']); expect(yaku.map((y) => y.id)).toEqual(expect.arrayContaining(['boar_deer_butterflies', 'cherry_viewing', 'moon_viewing'])); });
  it('automatically awakens only when HP falls below 100', () => {
    const prepareCapture = (hp: number) => { const game = initializeGame(['a', 'b'], `awake-${hp}`); const actor = game.activePlayerIndex; const defender = actor === 0 ? 1 : 0; const all = [...game.field, ...game.deck, ...game.players[0].hand, ...game.players[1].hand]; const played = '4-1'; const matched = '4-2'; const remaining = all.filter((id) => id !== played && id !== matched); const fieldFill = remaining.filter((id) => !id.startsWith('4-')).slice(0, 7); const pool = remaining.filter((id) => !fieldFill.includes(id)); game.players[actor].hand = [played, ...pool.splice(0, 7)]; game.players[defender].hand = pool.splice(0, 8); game.field = [matched, ...fieldFill]; game.deck = pool; game.players[actor].characterId = 'date_masamune'; game.players[defender].hp = hp; return { game, actor, defender }; };
    const below = prepareCapture(99); expect(reduceGame(below.game, below.game.players[below.actor].uid, { type: 'PLAY_CARD', cardId: '4-1' }).state.players[below.defender].awakened).toBe(true);
    const edge = prepareCapture(100); expect(reduceGame(edge.game, edge.game.players[edge.actor].uid, { type: 'PLAY_CARD', cardId: '4-1' }).state.players[edge.defender].awakened).toBe(false);
  });
  it('does not auto-play another hand card when the last hand card is played', () => {
    const game = initializeGame(['a', 'b'], 'last-card'); const actor = game.activePlayerIndex; const defender = actor === 0 ? 1 : 0; const played = '4-1'; const matched = '4-2'; const all = [...game.field, ...game.deck, ...game.players[0].hand, ...game.players[1].hand]; const rest = all.filter((id) => id !== played && id !== matched); game.players[actor].hand = [played]; game.players[defender].hand = rest.splice(0, 8); game.field = [matched, ...rest.splice(0, 7)]; game.deck = rest; const result = reduceGame(game, game.players[actor].uid, { type: 'PLAY_CARD', cardId: played }); expect(result.events.filter((event) => event.type === 'PLAY_CARD')).toHaveLength(1); expect(result.events.some((event) => event.type === 'AUTO_DRAW')).toBe(false); });
  it('redeals at a double hand-out without resetting HP', () => {
    const game = initializeGame(['a', 'b'], 'double-empty'); const actor = game.activePlayerIndex; const defender = actor === 0 ? 1 : 0; const used = new Set(['4-3', '4-4', '1-1', '2-1', '3-1', '4-1', '5-1', '6-1', '7-1', '8-1', '9-1', '10-1']); const remaining = CARDS.map((card) => card.id).filter((id) => !used.has(id)); game.players[actor].hand = ['4-3']; game.players[defender].hand = ['4-4']; game.field = ['1-1', '2-1', '3-1', '4-1', '5-1', '6-1', '7-1', '8-1']; game.deck = ['9-1', '10-1', ...remaining]; game.players[0].hp = 240; game.players[1].hp = 180; game.players[0].characterId = 'tokugawa_ieyasu'; game.players[1].characterId = 'tokugawa_ieyasu'; game.players[0].awakened = false; game.players[1].awakened = false; const first = reduceGame(game, game.players[actor].uid, { type: 'PLAY_CARD', cardId: '4-3' }); const second = reduceGame(first.state, first.state.players[first.state.activePlayerIndex].uid, { type: 'PLAY_CARD', cardId: '4-4' }); expect(second.state.status).toBe('ACTIVE'); expect(second.state.players[0].hand).toHaveLength(8); expect(second.state.players[1].hand).toHaveLength(8); expect(second.state.players[0].hp).toBe(240); expect(second.state.players[1].hp).toBe(180); expect(second.events.some((event) => event.type === 'ROUND_DRAW')).toBe(true); });
  it('finishes on forfeit and timeout', () => { const game = initializeGame(['a', 'b'], 'end', 0); expect(forfeitGame(game, 'a').winnerUid).toBe('b'); expect(timeoutGame(game, 60_001).finishReason).toBe('TIMEOUT'); });
});
